services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=portfolio'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=abcd1234'
      - 'MYSQL_USER=user'
    ports:
      - '3307:3306'